[tool.poetry]
name = "wagtail_issue_5248"
version = "0.1.0"
description = ""
authors = ["germn <Gerasimov-M-N@yandex.ru>"]

[tool.poetry.dependencies]
python = "^3.7"
wagtail = "^2.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
